ALTER TABLE introduction
    ADD COLUMN updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE introduction
    MODIFY COLUMN uploaded TIMESTAMP NULL;


ALTER TABLE introduction
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT false;


ALTER TABLE about
    ADD COLUMN updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP();


ALTER TABLE about
    MODIFY COLUMN uploaded TIMESTAMP NULL;

ALTER TABLE about
    ADD COLUMN active BOOLEAN not null DEFAULT false;

